/**
 * Generates a Shopify section .liquid template.
 */
export const sectionLiquid = (name: string): string => {
  const className = name;
  const title = name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

  return `{% comment %}
  ${title} Section
  Generated by ShopifyLabs CLI
{% endcomment %}

{{ '${name}.css' | asset_url | stylesheet_tag }}

<div class="${className}" id="section-${name}">
  <div class="${className}__container">
    <h2 class="${className}__heading">{{ section.settings.heading }}</h2>

    {% if section.settings.subheading != blank %}
      <p class="${className}__subheading">{{ section.settings.subheading }}</p>
    {% endif %}

    <div class="${className}__content">
      {{ section.settings.content }}
    </div>
  </div>
</div>

<script src="{{ '${name}.js' | asset_url }}" defer="defer"></script>

{% schema %}
{
  "name": "${title}",
  "tag": "section",
  "class": "section-${name}",
  "settings": [
    {
      "type": "text",
      "id": "heading",
      "label": "Heading",
      "default": "${title}"
    },
    {
      "type": "text",
      "id": "subheading",
      "label": "Subheading"
    },
    {
      "type": "richtext",
      "id": "content",
      "label": "Content"
    }
  ],
  "presets": [
    {
      "name": "${title}"
    }
  ]
}
{% endschema %}
`;
};

/**
 * Generates a starter JavaScript file for a Shopify section.
 */
export const sectionJs = (name: string): string => {
  const className = name;

  return `/**
 * ${name
   .split("-")
   .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
   .join(" ")} Section
 * Generated by ShopifyLabs CLI
 */

const init = () => {
  const section = document.querySelector('.${className}');

  if (!section) return;

  // Add your section logic here
  console.log('[ShopifyLabs] ${name} section initialized');
};

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}

export { init };
`;
};

/**
 * Generates a starter CSS file for a Shopify section.
 */
export const sectionCss = (name: string): string => {
  const className = name;

  return `/* ─────────────────────────────────────────────
   ${name
     .split("-")
     .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
     .join(" ")} Section
   Generated by ShopifyLabs CLI
   ───────────────────────────────────────────── */

.${className} {
  padding: 2rem 0;
}

.${className}__container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1.5rem;
}

.${className}__heading {
  margin: 0 0 1rem;
}

.${className}__subheading {
  margin: 0 0 1.5rem;
  opacity: 0.75;
}

.${className}__content {
  /* Add your styles here */
}
`;
};
