name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.4

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint & Format Check
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
